//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EbalitWebForms
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlogComment
    {
        public int Id { get; set; }
        public int FK_BlogEntry { get; set; }
        public string Subject { get; set; }
        public string Content { get; set; }
        public string UserName { get; set; }
        public string eMail { get; set; }
        public System.DateTime PostedOn { get; set; }
    
        public virtual BlogEntry BlogEntry { get; set; }
    }
}
