//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace EbalitWebForms.GUI {
    
    
    public partial class WebForm3 {
        
        /// <summary>
        /// CategoryBrowser control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EbalitWebForms.GUI.WebUserControls.CategoryBrowser CategoryBrowser;
        
        /// <summary>
        /// BlogContentUserControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EbalitWebForms.GUI.WebUserControls.BlogContentUserControl BlogContentUserControl;
        
        /// <summary>
        /// SearchUserControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EbalitWebForms.GUI.WebUserControls.SearchUserControl SearchUserControl;
    }
}
