//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EbalitWebForms.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlogTopic
    {
        public BlogTopic()
        {
            this.BlogCategories = new HashSet<BlogCategory>();
        }
    
        public int Id { get; set; }
        public string Topic { get; set; }
    
        public virtual ICollection<BlogCategory> BlogCategories { get; set; }
    }
}
