//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EbalitWebForms.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ErroneousWorkingReport
    {
        public int Id { get; set; }
        public string ProjectName { get; set; }
        public string ResourceName { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<decimal> WorkingTime { get; set; }
        public string TfsTaskId { get; set; }
        public string Description { get; set; }
    }
}
