//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EbalitWebForms.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectUserAssignment
    {
        public int Id { get; set; }
        public Nullable<int> ResourceId { get; set; }
        public string MembershipUserName { get; set; }
    
        public virtual ProjectResource ProjectResource { get; set; }
    }
}
