//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EbalitWebForms.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectWorkingReport
    {
        public int Id { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public Nullable<int> ResourceId { get; set; }
        public Nullable<int> TaskId { get; set; }
        public Nullable<System.DateTime> From { get; set; }
        public Nullable<System.DateTime> To { get; set; }
        public string Notes { get; set; }
        public Nullable<decimal> Total { get; set; }
    
        public virtual ProjectProject ProjectProject { get; set; }
        public virtual ProjectResource ProjectResource { get; set; }
        public virtual ProjectTask ProjectTask { get; set; }
    }
}
