//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EbalitWebForms.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class WineConsumation
    {
        public int Id { get; set; }
        public string Taster { get; set; }
        public Nullable<System.DateTime> TastedOn { get; set; }
        public string WeatherConditions { get; set; }
        public int FK_Wine { get; set; }
        public string Meal { get; set; }
        public Nullable<int> Rating { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ChangedOn { get; set; }
        public string ChangedBy { get; set; }
    
        public virtual Wine Wine { get; set; }
    }
}
